### ISSUE TITLE
Interceptor no longer works with Mail 2.5.4

### ISSUE THREAD

**Issue by carsonreinke** [jhawthorn/dkim#8]
I receive `undefined method 'field_order_id'`.  It looks like the problem is adding to `header.fields` requires a Mail::Field object, which is obviously is looking for `field_order_id`.  As far as I understand, this would require appending the Dkim field to  Mail::Field::FIELDS_MAP so that Mail::Field maps to the proper object.

I can put in a pull request if that seems like the right approach, though not a big fan of the global registration of the field.
